version: '3'

networks:
  rabbitnet:
    name: rabbitnet
    driver: bridge

services:
  rabbitmq:
    image: docker.io/rabbitmq:3.11.4-management
    container_name: rocketmq
    restart: always
    hostname: scan_tx_rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "45672:5672"
      - "35672:15672" # rabbitmq management
    networks:
      - rabbitnet
